---
db_username: modiwan_user

db_password: md5hashPassword

db_name: pg_dataCollector

db_port: 5432

db_user_expire: infinity

db_role_attr: CREATEDB,CREATEROLE,SUPERUSER

db_dependencies:
  - bash
  - openssl
  - libssl-dev
  - libssl-doc

db_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - python-psycopg2

on_db_remove_perform_dump: yes

on_db_remove_purge_package: yes

on_db_remove_purge_deps: False

db_dump_path: /var/tmp/

