---

#
# the services definition are stored in services/ in the same root dir as this file 
#

# If True the debug mode is enabled default value is False
enable_debug_mode: False

# This mean that all files of the deployment are not stored in the local machine (Ansible machine)
artifactories_are_not_in_local: False

# Path where we store the artificatories in the local machine (Ansible machine)
# The path is relative to the init_services.yml position
artifactories_local_path: ../../files/arch

# The default path is /lib/systemd/system/ and here we store all services configurations files
services_path: /var/tmp

# Here we store the downloaded files
download_root_path: /tmp

# When True all downloaded files will be deleted after the playbook success
cleanup_download_when_finish: True

