---
- name: '[0_0] - Nginx servers initialization'
  hosts: nginx-proxy
  remote_user: ansible-adm
  become: yes
  gather_facts: yes
  vars_files:
    - ../../vars/main.yml
    - ../../vars/nginx_settings.yml
  tasks:
    - name: Install nginx deps packages
      apt:
         name: "{{ nginx_deps }}"
         update_cache: yes
         state: latest
      tags: install-nginx-deps
      when: nginx_deps_needed and ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install nginx
      apt:
         name: "{{ nginx_package }}"
         state: present
      tags: install-nginx
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


    - name: Install nginx deps packages
      yum:
         name: "{{ nginx_deps }}"
         update_cache: yes
         state: latest
      tags: install-nginx-deps
      when: nginx_deps_needed and ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Install nginx
      yum:
         name: "{{ nginx_package }}"
         state: present
      tags: install-nginx
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'



    - name: Configure nginx
      template:
         src: ../../templates/nginx-config-file.j2
         dest: /etc/nginx/nginx-configuration-file.conf
      tags: configure-nginx

    - name: Configure nginx proxy server
      template:
         src: ../../templates/nginx-proxy-config-file.j2
         dest: /etc/nginx/conf.d/nginx-proxy-configuration-file.conf

    - name: Start nginx service 
      service:
         name: nginx
         state: started
         enabled: yes
      tags: start-nginx

# you can add tasks like this
#    - import_tasks: tasks/common/get_hostname.yml
